import Candidatos from "../model/Candidatos"

export let datosCandidatos: Candidatos[] = [
    {
    id: 1,
    nombreCompleto: "ALFONSO JUAREZ",
    especializacionLaboral: "ANALISTA EN SISTEMA",
    edad: 30,
    habilidadUno: "LIDERAZGO",
    habilidadDos: "MANEJO DE OFFICE COMPLETO",
    habilidadTres: "INGLÉS AVANZADO",
    habilidadCuatro: "HABILIDAD DE NEGOCIACION",
    infoExtraUno: "SI",
    infoExtraDos: "SI",
    linkedin: "",
    imagen:"/imagenes/imagenesCandidatos/ALFONSOJUAREZ.jpg"
},
{
    id: 2,
    nombreCompleto: "ELENA RODRIGUEZ",
    especializacionLaboral: "TRABAJADORA SOCIAL",
    edad: 27,
    habilidadUno: "HABILIDAD COMUNICATIVA",
    habilidadDos: "RESPONSABILIDAD",
    habilidadTres: "CAPACIDAD DE PROYECTAR",
    habilidadCuatro: "INGLÉS INTERMEDIO",
    infoExtraUno: "NO",
    infoExtraDos: "SI",
    linkedin: "",
    imagen:"/imagenes/imagenesCandidatos/ELENARODRIGUEZ.jpg"
},
{
    id: 3,
    nombreCompleto: "LUCAS PEREZ",
    especializacionLaboral: "PROFESOR DE EDUCACIÓN FÍSICA",
    edad: 41,
    habilidadUno: "ACTITUD POSITIVA",
    habilidadDos: "FRANCES E INGLÉS INTERMEDIO",
    habilidadTres: "CLASES GRUPALES Y PARTICULARES",
    habilidadCuatro: "INNOVACÓN",
    infoExtraUno: "NO",
    infoExtraDos: "SI",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/LUCASPEREZ.jpg",

},
{
    id: 4,
    nombreCompleto: "TAMARA BENITEZ",
    especializacionLaboral: "PROFESORA DE EDUCACIÓN INICIAL",
    edad: 33,
    habilidadUno: "CREATIVIDAD",
    habilidadDos: "CAPACIDAD DE OBSERVACIÓN",
    habilidadTres: "RESPONSABILIDAD",
    habilidadCuatro: "ELABORACIÓN DE MATERIALES DIDÁCTICOS",
    infoExtraUno: "SI",
    infoExtraDos: "NO",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/TAMARABENITEZ.jpg",
},
{
    id: 5,
    nombreCompleto: "FÁTIMA CHAVEZ",
    especializacionLaboral: "ODONTÓLOGA",
    edad: 45,
    habilidadUno: "ESTÉTICA BUCAL",
    habilidadDos: "HONESTIDAD E INTEGRIDAD",
    habilidadTres: "CAPACIDAD ORGANIZATIVA",
    habilidadCuatro: "TECNOLOGÍA AVANZADA",
    infoExtraUno: "SI",
    infoExtraDos: "SI",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/FATIMACHAVEZ.jpg",
},
{
    id: 6,
    nombreCompleto: "RODRIGO GÓMEZ",
    especializacionLaboral: "CHEF PROFESIONAL",
    edad: 52,
    habilidadUno: "TRABAJO EN EQUIPO",
    habilidadDos: "SEGURIDAD E HIGIENE ALIMENTARIA",
    habilidadTres: "PRESICIÓN Y RESPONSABILIDAD",
    habilidadCuatro: "ITALIANO E INGLÉS AVANZADO",
    infoExtraUno: "SI",
    infoExtraDos: "SI",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/RODRIGOGOMEZ.jpg",

},
{
    id: 7,
    nombreCompleto: "LIONEL MARTINEZ",
    especializacionLaboral: "LIC. EN ADMINISTRACIÓN DE EMPRESAS",
    edad: 34,
    habilidadUno: "TRABAJO REMOTO E HÍBRIDO",
    habilidadDos: "INGLÉS AVANZADO",
    habilidadTres: "CAPACIDAD PARA TRABAJAR EN EQUIPO",
    habilidadCuatro: "SERVICIOS DE ATENCIÓN AL CLIENTE",
    infoExtraUno: "SI",
    infoExtraDos: "NO",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/LIONELMARTINEZ.jpg",

},
{
    id: 8,
    nombreCompleto: "ÁLVARO DÍAZ",
    especializacionLaboral: "FOTÓGRAFO PROFESIONAL Y FILMMAKER",
    edad: 18,
    habilidadUno: "CREATIVO Y DINÁMICO",
    habilidadDos: "BUEN MANEJO DE ADOBE",
    habilidadTres: "HABILIDAD COMUNICATIVA",
    habilidadCuatro: "INGLÉS INTERMEDIO",
    infoExtraUno: "SI",
    infoExtraDos: "NO",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/ALVARODIAZ.jpg",
},
{
    id: 9,
    nombreCompleto: "JIMENA FERNÁNDEZ",
    especializacionLaboral: "CHÓFER DE EQUIPOS MÓVILES",
    edad: 24,
    habilidadUno: "CONOCIMIENTOS MECÁNICOS",
    habilidadDos: "BUENA PREDISPOSICIÓN",
    habilidadTres: "COMUNICACIÓN EFECTIVA",
    habilidadCuatro: "INGLÉS AVANZADO",
    infoExtraUno: "SI",
    infoExtraDos: "NO",
    linkedin: "",
    imagen: "/imagenes/imagenesCandidatos/JIMENAFERNANDEZ.jpg",
},
]
